### ISSUE TITLE
mgo.v2 is unmaintained

### ISSUE THREAD

**Issue by tomasol** [flaviostutz/schellar#3]
Currently used mongo driver is [not maintained anymore](https://godoc.org/gopkg.in/mgo.v2). Are there plans to move to something else?

**Comment by flaviostutz** [comment]
Hi, @tomasol, I didn’t know it was not maintained anymore. Thanks for the information. Are you into any issues? There is a built container that must be working at “flaviostutz/schellar”.

**Comment by tomasol** [comment]
Hi, not really. I am considering your project for conductor scheduling, I found no problems during my initial testing. Feel free to close the issue.

**Comment by flaviostutz** [comment]
Great. If you need any assistance come here. PRs are welcome too!
