### ISSUE TITLE
Creating schedule with name containing '/' character

### ISSUE THREAD

**Issue by tomasol** [flaviostutz/schellar#4]
It is possible to create a schedule with `/`, however then it becomes impossible to delete it. Error I get is 404. Possible solution is to disallow this character when creating schedules.

**Comment by flaviostutz** [comment]
This is probably due to URL parsing. Good idea desallowing this char during creation!
I will look for this when I have time. If you would like to help, PRs will be gladly accepted ;)

**Comment by flaviostutz** [comment]
Hi, @tomasol, please test the latest version at flaviostutz/schellar:latest and check if this was solved before I tag it.

Thanks for the help!

**Comment by tomasol** [comment]
Thanks, it works ;)
