### ISSUE TITLE
Not possible to create a disabled schedule

### ISSUE THREAD

**Issue by tomasol** [flaviostutz/schellar#5]
I tried POSTing following:
```json
{
"name": "seconds-tests1",
"cronString": "0 * * ? * *",
"workflowName": "encode_and_deploy",
"workflowVersion": "1"
}
```
```json
{
"name": "seconds-tests2",
"cronString": "0 * * ? * *",
"workflowName": "encode_and_deploy",
"workflowVersion": "1",
"enabled":false
}
```
However both produce a schedule with `enabled` set to `true`.

**Comment by flaviostutz** [comment]
@tomasol Thanks for the notice. During creation it always use enabled=true. I removed this behavior so that the caller must send enabled=true in order to be enabled.

Please test the latest version with the fix in 
flaviostutz/schellar:latest before I tag it.

**Comment by tomasol** [comment]
Awesome, it works. Thanks. For your notice, I have integrated schellar [here](https://github.com/facebookincubator/magma/blob/master/symphony/integration/docker-compose.conductor.frinx.yaml#L73)

**Comment by flaviostutz** [comment]
Great to know! Glad to help.

**Comment by flaviostutz** [comment]
Tagged version 1.3.0 with newest commits
